spring.application.name=bff-scheduler


user.url=localhost:8080/user
taskManager.url=localhost:8081/task
notification.url=localhost:8084/email
cron.time=0 0/5 * * * ?
user.email=admin@admin.com
user.password=1234

server.port=8085